[package]
name = "delta_executor"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.9"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde = "1.0"
serde_json = "1.0"